name: CI

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      name:
        description: "Manual trigger"
  schedule:
    - cron:  '0 4 * * *'

jobs:

  micro_ros_mbed:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    strategy:
      matrix:
        mbed_version: [mbed-os-6.8.0, mbed-os-6.9.0, mbed-os-6.10.0]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          path: micro_ros_mbed

      - name: Dependencies
        shell: bash
        run: |
          apt update
          export DEBIAN_FRONTEND=noninteractive
          apt install -y git gcc-arm-none-eabi python3 python3-pip sudo git curl apt-transport-https ca-certificates gnupg software-properties-common wget ninja-build cmake
          # Install colcon
          pip3 install catkin_pkg lark-parser empy colcon-common-extensions
          pip3 install mbed-tools

      - name: Build sample - int32_publisher
        shell: bash
        run: |
          cd micro_ros_mbed
          echo https://github.com/ARMmbed/mbed-os/\#${{ matrix.mbed_version }} > mbed-os.lib
          mbed-tools deploy
          mbed-tools compile -m DISCO_L475VG_IOT01A -t GCC_ARM
